[package]
name = "dq10tools"
version = "0.1.0"
authors = ["hisanori <hisary@gmail.com>"]
edition = "2018"

[[bin]]
name = "holy-war-in-the-eternal-darkness"
path = "src/eternal_darkness/main.rs"

[[bin]]
name = "record-of-the-saint-guardians-war"
path = "src/saint_guardians/main.rs"

[dependencies]
serde_json = "1.0"
chrono = "0.4"
